# Generated by Django 5.1 on 2024-11-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('redes_sociales', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
